version: "3.5"
services:
  app:
    image: igor875126/project-zomboid:latest
    build:
      dockerfile: "Dockerfile"
      context: .
    container_name: project-zomboid
    restart: unless-stopped
    ports:
      - "8766:8766/udp"
      - "8767:8767/udp"
      - "16261:16261/udp"
      - "16262:16262/udp"
      - "27015:27015/tcp"
      - "16262-16272:16262-16272/tcp"
    volumes:
      - "./steam:/root/Steam"
      - "./server-files:/root/ProjectZomboidServer"
      - "./server-configs:/root/Zomboid/Server"
    environment: 
      - SERVER_NAME=ZomboidDocker
      - ADMIN_PASSWORD=Zomboid20232023
      - ALLOWED_RAM_IN_GB=1